### ISSUE TITLE
Online multilayer corpus annotation editing tool

### ISSUE THREAD

**Issue by somiyagawa** [KELLIA/kellia.github.io#1]
Today, Heike, Ulrich and I discussed the KELLIA homepage. We have a question about Online multilayer corpus annotation editing tool on "Products" page. Does it mean GitDox? Can I write about it instead of this old description? Or could you update it?

**Comment by ctschroeder** [comment]
Description with links added!

**Comment by amir-zeldes** [comment]
Thanks!
